---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-parson-one
  labels:
    app: java-parson-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-parson-one
  template:
    metadata:
      labels:
        app: java-parson-one
    spec:
      containers:
        - name: java-parson-one
          image: docker.io/parsontodd/java-parson-one:latest
          ports:
            - containerPort: 8080